### ISSUE TITLE
Lambda Days 2020 - Q&A

### ISSUE THREAD

**Issue by brucou** [willheslam/runic-prototype#1]
Hi William,

I am an editor for InfoQ, covering the Lambda Days 2020 event. Would you be interested in doing a Q&A related to your presentation there called *Modelling Side Effects via Extensible Effects*? To give an idea of what that can looks like, here are:
- an example of previous Q&A (on a WebAssembly port): https://www.infoq.com/news/2019/07/doom3-web-assembly-port/
- coverage of John Hughes presentation at the same event: https://www.infoq.com/news/2020/02/property-based-testing-guide/

As you can see that takes the form of a few questions, and should not take too much of your time. I believe the subject itself is of value for our readers (mostly tech leads and software architects), specially so as it uses plain JavaScript to illustrate the concepts and techniques. 

Please let me know if that is of interest to you.
Best regards,

**Comment by willheslam** [comment]
Hi @brucou,

Thanks for getting in touch, that sounds fun! I'd be very happy to answer some questions.

I realised I didn't have my email on my profile - feel free to email me there: https://github.com/willheslam

Thanks!

**Comment by brucou** [comment]
Amazing! Thanks for the interest. I would rather however continue through email than github. Could you write me at olivier.couriol@gmail.com so I get your email? (I'll then delete this post so my email is not picked up by some malicious bots).

**Comment by brucou** [comment]
Alright I am closing this then now.
